version: '3.5'

services:
  postgres:
    image: "postgres:12.0"
    volumes:
      - postgres:/var/lib/postgresql/data
  
  redis:
    image: "redis:4.0-alpine"
    command: redis-server
    ports:
      - "5152:5152"
    volumes:
      - redis:/var/lib/redis/data
  
  app:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3001:3000"
    volumes:
      - .:/onebittwitter
      - app-gems:/app-gems
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
    stdin_open: true
    tty: true
  
  jobs:
    depends_on:
      - "postgres"
      - "redis"
      - "app"
      - "elasticsearch"
    build: .
    command: bash start_jobs.sh
    volumes:
      - .:/onebittwitter
      - app-gems:/app-gems
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200

  elasticsearch:
    image: "elasticsearch:5"
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - Des.network.host=0.0.0.0

volumes:
  redis:
  postgres:
  app-gems:
  app-gems:
  elastic: