default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres

development:
  <<: *default
  database: one_bit_twitter_development

test:
  <<: *default
  database: one_bit_twitter_test

production:
  database: one_bit_twitter_test
  username: OneBitTwitter
  password: <%= ENV['ONEBITTWITTER_DATABASE_PASSWORD'] %>